export const EDGE_OPTIONS = [
  { id: "origin", label: "오리진" },
  { id: "gold", label: "골드" },
  { id: "signature", label: "시그니처" },
  { id: "egg", label: "에그타르트" },
  { id: "cream", label: "크림치즈" },
  { id: "cheesecap", label: "치즈캡" },
  { id: "thin", label: "씬" },
  { id: "noedge", label: "노엣지" },
];

export const EDGE_PRICE_MAP = {
  classic: {
    origin: 0,
    signature: 2000,
    cheesecap: 5000,
    noedge: 0,
  },
  premium: {
    gold: 0,
    signature: 0,
    egg: 0,
    cream: 0,
    cheesecap: 3500,
  },
  suncrust: {
    thin: 0,
  },
};

export const RAW_ITEMS = [
  {
    id: 1,
    img: "/resources/images/component/menu/pizza-premium/pizza_premium_01.png",
    category: "프리미엄 피자",
    line: "premium",
    title: "스페셜콰트로",
    price: "M 32,500 · L 39,500",
    pick: "네 가지 시그니처의 완벽한 밸런스",
    desc: "포테이토골드 · 쉬림프골드 · 콰트로치즈 · 스윗고구마를 한 판에 담은 미스터피자 대표 믹스.",
    tags: ["NEW", "SIGNATURE", "4 QUARTERS"],
    line: "premium",
    defaultEdge: "gold",
    allowedEdges: ["gold", "signature", "egg", "cream", "cheesecap"],
    originInfo: "미트토핑: 돼지고기(지방일부/국산), 쇠고기(호주산), 베이컨: 돼지고기(외국산)",
    nutritionInfo: {
      M: { kcal: 239, protein: 10, sodium: 394 },
      L: { kcal: 376, protein: 16, sodium: 630 },
    },
    allergyInfo: "난류, 우유, 대두, 밀, 새우, 돼지고기, 토마토, 쇠고기, 땅콩 함유",
  },
  {
    id: 2,
    img: "/resources/images/component/menu/pizza-premium/pizza_premium_02.png",
    category: "프리미엄 피자",
    line: "premium",
    title: "미스터트리오",
    price: "M 32,500 · L 39,500",
    pick: "세 가지 시그니처의 완성형 조합",
    desc: "풍성한 토핑과 깊은 풍미가 어우러진 트리플 레이어. 고기, 치즈, 소스의 밸런스를 한 번에 즐기는 프리미엄 블렌드.",
    tags: ["TRIO", "PREMIUM", "BALANCED"],
    defaultEdge: "gold",
    allowedEdges: ["gold", "signature", "egg", "cream", "cheesecap"],
  },
  {
    id: 3,
    img: "/resources/images/component/menu/pizza-premium/pizza_premium_03.png",
    category: "프리미엄 피자",
    line: "premium",
    title: "치즈블라썸스테이크",
    price: "M 32,500 · L 39,500",
    pick: "꽃처럼 피어난 스테이크의 존재감",
    desc: "육즙 가득 스테이크와 치즈 블라썸이 만나 비주얼과 맛을 동시에 압도하는 시그니처.",
    tags: ["STEAK", "BLOSSOM", "SIGNATURE"],
    defaultEdge: "gold",
    allowedEdges: ["gold", "signature", "egg", "cream", "cheesecap"],
  },
  {
    id: 4,
    img: "/resources/images/component/menu/pizza-classic/pizza_classic_01.png",
    category: "클래식 피자",
    line: "classic",
    title: "스윗고구마",
    price: "M 21,900 · L 28,900",
    pick: "달콤함이 먼저 오는 클래식",
    desc: "부드러운 고구마 무스와 크리미한 소스가 만들어내는 편안하고 깊은 단맛의 밸런스.",
    tags: ["SWEET", "CREAMY", "CLASSIC"],
    defaultEdge: "origin",
    allowedEdges: ["origin", "signature", "cheesecap"],
  },
  {
    id: 5,
    img: "/resources/images/component/menu/pizza-premium/pizza_premium_04.png",
    category: "프리미엄 피자",
    line: "premium",
    title: "디아볼라블라썸",
    price: "M 29,500 · L 36,500",
    pick: "부드러움 속 강렬한 반전",
    desc: "매콤한 살라미와 스파이시 소스가 치즈 블라썸과 어우러진 매혹적인 매운맛.",
    tags: ["SPICY", "SALAMI", "BLOSSOM"],
    defaultEdge: "gold",
    allowedEdges: ["gold", "signature", "egg", "cream", "cheesecap"],
  },
  {
    id: 6,
    img: "/resources/images/component/menu/pizza-premium/pizza_premium_05.png",
    category: "프리미엄 피자",
    line: "premium",
    title: "레전드 포테이토",
    price: "M 31,500 · L 38,500",
    desc: "두툼한 감자와 달콤한 크림소스, 그리고 베이컨의 황금 밸런스. 클래식을 넘어선 ‘레전드’ 조합.",
    tags: ["POTATO", "CLASSIC HERO", "BEST SELLER"],
    defaultEdge: "gold",
    allowedEdges: ["gold", "signature", "egg", "cream", "cheesecap"],
  },
  {
    id: 7,
    img: "/resources/images/component/menu/pizza-classic/pizza_classic_02.png",
    category: "클래식 피자",
    line: "classic",
    title: "더블치즈",
    price: "M 21,900 · L 28,900",
    pick: "치즈의 본질에 집중하다",
    desc: "두 배로 녹아내리는 치즈의 풍미. 불필요한 장식 없이 깊고 진한 고소함을 그대로 담은 클래식의 정석.",
    tags: ["CHEESE", "CLASSIC", "RICH"],
    defaultEdge: "origin",
    allowedEdges: ["origin", "signature", "cheesecap"],
  },
  {
    id: 8,
    img: "/resources/images/component/menu/pizza-premium/pizza_premium_06.png",
    category: "프리미엄 피자",
    line: "premium",
    title: "쉬림프골드",
    price: "M 32,500 · L 39,500",
    pick: "탱글한 쉬림프의 정석",
    desc: "버터 갈릭의 고소함과 풍성한 치즈가 어우러진 깊이 있는 프리미엄 씨푸드.",
    tags: ["BEST", "SEAFOOD", "BUTTER GARLIC"],
    defaultEdge: "gold",
    allowedEdges: ["gold", "signature", "egg", "cream", "cheesecap"],
  },
  {
    id: 9,
    img: "/resources/images/component/menu/pizza-premium/pizza_premium_07.png",
    category: "프리미엄 피자",
    line: "premium",
    title: "포테이토골드",
    price: "M 31,500 · L 38,500",
    pick: "두툼한 감자의 정석, 변함없는 베스트",
    desc: "크리미한 감자무스와 고소한 베이컨, 달콤한 소스가 어우러진 미스터피자의 시그니처 클래식.",
    tags: ["BEST", "POTATO", "SIGNATURE"],
    defaultEdge: "gold",
    allowedEdges: ["gold", "signature", "egg", "cream"],
    originInfo: "미트토핑: 돼지고기(지방일부/국산), 쇠고기(호주산), 베이컨: 돼지고기(외국산)",
    nutritionInfo: {
      M: { kcal: 245, protein: 11, sodium: 410 },
      L: { kcal: 372, protein: 17, sodium: 645 },
    },
    allergyInfo: "난류, 우유, 대두, 밀, 돼지고기, 토마토, 쇠고기 함유",
  },
  {
    id: 10,
    img: "/resources/images/component/menu/pizza-premium/pizza_premium_08.png",
    category: "프리미엄 피자",
    line: "premium",
    title: "하프앤하프",
    price: "M 32,500 · L 39,500",
    pick: "",
    desc: "",
    tags: [],
    defaultEdge: "gold",
    allowedEdges: ["gold", "signature", "egg", "cream", "cheesecap"],
    originInfo: "미트토핑: 돼지고기(지방일부/국산), 쇠고기(호주산), 베이컨:돼지고기(외국산)",
    nutritionInfo: "",
    allergyInfo: "난류, 우유, 대두, 밀, 새우, 돼지고기, 토마토, 쇠고기 함유",
  },
  {
    id: 11,
    img: "/resources/images/component/menu/pizza-premium/pizza_premium_09.png",
    category: "프리미엄 피자",
    line: "premium",
    title: "크레이지 핫",
    price: "M 29,500 · L 36,500",
    pick: "",
    desc: "",
    tags: [],
    defaultEdge: "gold",
    allowedEdges: ["gold", "signature", "egg", "cream", "cheesecap"],
    originInfo: "",
    nutritionInfo: "",
    allergyInfo: "함유",
  },
  {
    id: 12,
    img: "/resources/images/component/menu/pizza-premium/pizza_premium_10.png",
    category: "프리미엄 피자",
    line: "premium",
    title: "콰트로치즈",
    price: "M 30,500 · L 37,500",
    pick: "",
    desc: "",
    tags: [],
    defaultEdge: "gold",
    allowedEdges: ["gold", "signature", "egg", "cream", "cheesecap"],
    originInfo: "",
    nutritionInfo: "",
    allergyInfo: "함유",
  },
  {
    id: 13,
    img: "/resources/images/component/menu/pizza-premium/pizza_premium_11.png",
    category: "프리미엄 피자",
    line: "premium",
    title: "레전드 바질 마스카포네",
    price: "M 29,500 · L 36,500",
    pick: "",
    desc: "",
    tags: [],
    defaultEdge: "gold",
    allowedEdges: ["gold", "signature", "egg", "cream", "cheesecap"],
    originInfo: "",
    nutritionInfo: "",
    allergyInfo: "함유",
  },
  {
    id: 14,
    img: "/resources/images/component/menu/pizza-premium/pizza_premium_12.png",
    category: "프리미엄 피자",
    line: "premium",
    title: "레전드 쉬림프",
    price: "M 32,500 · L 39,500",
    pick: "",
    desc: "",
    tags: [],
    defaultEdge: "gold",
    allowedEdges: ["gold", "signature", "egg", "cream", "cheesecap"],
    originInfo: "",
    nutritionInfo: "",
    allergyInfo: "함유",
  },
  {
    id: 15,
    img: "/resources/images/component/menu/pizza-premium/pizza_premium_13.png",
    category: "프리미엄 피자",
    line: "premium",
    title: "디아볼라블라썸",
    price: "M 29,500 · L 36,500",
    pick: "",
    desc: "",
    tags: [],
    defaultEdge: "gold",
    allowedEdges: ["gold", "signature", "egg", "cream", "cheesecap"],
    originInfo: "",
    nutritionInfo: "",
    allergyInfo: "함유",
  },
  {
    id: 16,
    img: "/resources/images/component/menu/pizza-premium/pizza_premium_14.png",
    category: "프리미엄 피자",
    line: "premium",
    title: "새우천왕",
    price: "M 32,500 · L 39,500",
    pick: "",
    desc: "",
    tags: [],
    defaultEdge: "gold",
    allowedEdges: ["gold", "signature", "egg", "cream", "cheesecap"],
    originInfo: "",
    nutritionInfo: "",
    allergyInfo: "함유",
  },
  {
    id: 17,
    img: "/resources/images/component/menu/pizza-classic/pizza_classic_03.png",
    category: "클래식 피자",
    line: "classic",
    title: "콘스노잉",
    price: "M 20,900 · L 27,900",
    pick: "",
    desc: "",
    tags: [],
    defaultEdge: "origin",
    allowedEdges: ["origin", "signature", "cheesecap"],
    originInfo: "",
    nutritionInfo: "",
    allergyInfo: "함유",
  },
  {
    id: 18,
    img: "/resources/images/component/menu/pizza-classic/pizza_classic_04.png",
    category: "클래식 피자",
    line: "classic",
    title: "치즈후라이",
    price: "M 21,900 · L 28,900",
    pick: "",
    desc: "",
    tags: [],
    defaultEdge: "origin",
    allowedEdges: ["origin", "signature", "cheesecap"],
    originInfo: "",
    nutritionInfo: "",
    allergyInfo: "함유",
  },
  {
    id: 19,
    img: "/resources/images/component/menu/pizza-classic/pizza_classic_05.png",
    category: "클래식 피자",
    line: "classic",
    title: "페퍼로니플러스",
    price: "M 19,900 · L 26,900",
    pick: "",
    desc: "",
    tags: [],
    defaultEdge: "origin",
    allowedEdges: ["origin", "signature", "cheesecap"],
    originInfo: "",
    nutritionInfo: "",
    allergyInfo: "함유",
  },
  {
    id: 20,
    img: "/resources/images/component/menu/pizza-classic/pizza_classic_06.png",
    category: "클래식 피자",
    line: "classic",
    title: "베지테리안",
    price: "M 19,900 · L 26,900",
    pick: "",
    desc: "",
    tags: [],
    defaultEdge: "origin",
    allowedEdges: ["origin", "signature", "cheesecap"],
    originInfo: "",
    nutritionInfo: "",
    allergyInfo: "함유",
  },
  {
    id: 21,
    img: "/resources/images/component/menu/pizza-classic/pizza_classic_07.png",
    category: "클래식 피자",
    line: "classic",
    title: "하와이안스페셜",
    price: "M 20,900 · L 27,900",
    pick: "",
    desc: "",
    tags: [],
    defaultEdge: "origin",
    allowedEdges: ["origin", "signature", "cheesecap"],
    originInfo: "",
    nutritionInfo: "",
    allergyInfo: "함유",
  },
  {
    id: 22,
    img: "/resources/images/component/menu/pizza-classic/pizza_classic_08.png",
    category: "클래식 피자",
    line: "classic",
    title: "콤비네이션",
    price: "M 21,900 · L 28,900",
    pick: "",
    desc: "",
    tags: [],
    defaultEdge: "origin",
    allowedEdges: ["origin", "signature", "cheesecap"],
    originInfo: "",
    nutritionInfo: "",
    allergyInfo: "함유",
  },
  {
    id: 23,
    img: "/resources/images/component/menu/pizza-classic/pizza_classic_09.png",
    category: "클래식 피자",
    line: "classic",
    title: "포테이토",
    price: "M 21,900 · L 28,900",
    pick: "",
    desc: "",
    tags: [],
    defaultEdge: "origin",
    allowedEdges: ["origin", "cheesecap"],
    originInfo: "",
    nutritionInfo: "",
    allergyInfo: "함유",
  },
  {
    id: 24,
    img: "/resources/images/component/menu/pizza-classic/pizza_classic_10.png",
    category: "클래식 피자",
    line: "classic",
    title: "불고기",
    price: "M 21,900 · L 28,900",
    pick: "",
    desc: "",
    tags: [],
    defaultEdge: "origin",
    allowedEdges: ["origin", "signature", "cheesecap"],
    originInfo: "",
    nutritionInfo: "",
    allergyInfo: "함유",
  },
  {
    id: 25,
    img: "/resources/images/component/menu/pizza-classic/pizza_classic_11.png",
    category: "클래식 피자",
    line: "classic",
    title: "시카고딥",
    price: "M 25,900 · L 31,900",
    pick: "",
    desc: "",
    tags: [],
    defaultEdge: "noedge",
    allowedEdges: ["noedge"],
    edgeLocked: true,
    originInfo: "",
    nutritionInfo: "",
    allergyInfo: "함유",
  },
  {
    id: 26,
    img: "/resources/images/component/menu/pizza-suncrust/pizza_suncrust_01.png",
    category: "씬크러스트 피자",
    line: "suncrust",
    title: "(씬)",
    price: "M 21,900 · L 28,900",
    pick: "",
    desc: "",
    tags: [],
    originInfo: "",
    nutritionInfo: "",
    allergyInfo: "함유",
  },
];

const HERO_IDS = new Set([1, 2, 3, 4, 5]);

const getHeroImgById = (id) => (HERO_IDS.has(id) ? `/resources/images/component/main/${id}.png` : null);

export const HERO_ITEMS = MENU_ITEMS.filter((item) => HERO_IDS.has(item.id)).map((item) => ({
  ...item,
  heroImg: getHeroImgById(item.id) ?? item.img,
}));

//////////////
const LINE_DEFAULTS = {
  suncrust: {
    defaultEdge: "thin",
    edgeLocked: true,
    allowedEdges: ["thin"],
  },
};

const withDefaults = (item) => ({
  ...item,
  ...(LINE_DEFAULTS[item.line] || {}),
});

export const MENU_ITEMS = RAW_ITEMS.map(withDefaults);
