export const MENU_ITEMS = [
  {
    id: 1,
    img: "/resources/images/component/menu/1.png",
    category: "프리미엄 피자",
    title: "스페셜콰트로",
    price: "L 39,500 · M 32,500",
    pick: "네 가지 시그니처의 완벽한 밸런스",
    desc: "포테이토골드 · 쉬림프골드 · 콰트로치즈 · 스윗고구마를 한 판에 담은 미스터피자 대표 믹스.",
    tags: ["NEW", "SIGNATURE", "4 QUARTERS"],
  },
  {
    id: 2,
    img: "/resources/images/component/menu/2.png",
    category: "프리미엄 피자",
    title: "미스터트리오",
    price: "L 39,500 · M 32,500",
    pick: "세 가지 시그니처의 완성형 조합",
    desc: "풍성한 토핑과 깊은 풍미가 어우러진 트리플 레이어. 고기, 치즈, 소스의 밸런스를 한 번에 즐기는 프리미엄 블렌드.",
    tags: ["TRIO", "PREMIUM", "BALANCED"],
  },
  {
    id: 3,
    img: "/resources/images/component/menu/3.png",
    category: "프리미엄 피자",
    title: "치즈블라썸스테이크",
    price: "L 39,500 · M 32,500",
    pick: "꽃처럼 피어난 스테이크의 존재감",
    desc: "육즙 가득 스테이크와 치즈 블라썸이 만나 비주얼과 맛을 동시에 압도하는 시그니처.",
    tags: ["STEAK", "BLOSSOM", "SIGNATURE"],
  },
  {
    id: 4,
    img: "/resources/images/component/menu/4.png",
    category: "클래식 피자",
    title: "스윗고구마",
    price: "L 28,900 · M 21,900",
    pick: "달콤함이 먼저 오는 클래식",
    desc: "부드러운 고구마 무스와 크리미한 소스가 만들어내는 편안하고 깊은 단맛의 밸런스.",
    tags: ["SWEET", "CREAMY", "CLASSIC"],
  },
  {
    id: 5,
    img: "/resources/images/component/menu/5.png",
    category: "프리미엄 피자",
    title: "디아볼라블라썸",
    price: "L 36,500 · M 29,500",
    pick: "부드러움 속 강렬한 반전",
    desc: "매콤한 살라미와 스파이시 소스가 치즈 블라썸과 어우러진 매혹적인 매운맛.",
    tags: ["SPICY", "SALAMI", "BLOSSOM"],
  },
  {
    id: 6,
    img: "/resources/images/component/menu/6.png",
    category: "프리미엄 피자",
    title: "레전드 포테이토",
    price: "L 38,500 · M 31,500",
    desc: "두툼한 감자와 달콤한 크림소스, 그리고 베이컨의 황금 밸런스. 클래식을 넘어선 ‘레전드’ 조합.",
    tags: ["POTATO", "CLASSIC HERO", "BEST SELLER"],
  },
  {
    id: 7,
    img: "/resources/images/component/menu/2.png",
    category: "클래식 피자",
    title: "더블치즈",
    price: "L 28,900 · M 21,900",
    pick: "치즈의 본질에 집중하다",
    desc: "두 배로 녹아내리는 치즈의 풍미. 불필요한 장식 없이 깊고 진한 고소함을 그대로 담은 클래식의 정석.",
    tags: ["CHEESE", "CLASSIC", "RICH"],
  },
  {
    id: 8,
    img: "/resources/images/component/menu/2.png",
    category: "프리미엄 피자",
    title: "쉬림프골드",
    price: "L 39,500 · M 32,500",
    pick: "탱글한 쉬림프의 정석",
    desc: "버터 갈릭의 고소함과 풍성한 치즈가 어우러진 깊이 있는 프리미엄 씨푸드.",
    tags: ["BEST", "SEAFOOD", "BUTTER GARLIC"],
  },
];

const HERO_IDS = new Set([1, 2, 3, 4, 5]);

const getHeroImgById = (id) => (HERO_IDS.has(id) ? `/resources/images/component/main/${id}.png` : null);

export const HERO_ITEMS = MENU_ITEMS.filter((item) => HERO_IDS.has(item.id)).map((item) => ({
  ...item,
  heroImg: getHeroImgById(item.id) ?? item.img,
}));
