export const EDGE_OPTIONS = [
  { id: "origin", label: "오리진" },
  { id: "gold", label: "골드" },
  { id: "signature", label: "시그니처" },
  { id: "egg", label: "에그타르트" },
  { id: "cream", label: "크림치즈" },
  { id: "cheesecap", label: "치즈캡" },
  { id: "thin", label: "씬" },
  { id: "noedge", label: "노엣지" },
];

export const EDGE_PRICE_MAP = {
  classic: {
    origin: 0,
    signature: 2000,
    cheesecap: 5000,
    noedge: 0,
  },
  premium: {
    gold: 0,
    signature: 0,
    egg: 0,
    cream: 0,
    cheesecap: 3500,
  },
  suncrust: {
    thin: 0,
  },
};

export const PIZZA_LINE_LABELS = {
  premium: "프리미엄",
  classic: "클래식",
  suncrust: "씬크러스트",
  solo: "1인용",
};

export const SIDE_LINE_LABELS = {
  pizzasand: "피자샌드",
  pasta: "파스타 & 라이스",
  salad: "샐러드 & 사이드",
  drink: "음료",
};

export const SET_LINE_LABELS = {
  special: "특제 세트",
};

export const RAW_ITEMS = [
  {
    id: 1,
    img: "/mr-pizza/resources/images/component/menu/pizza-premium/pizza_premium_01.png",
    category: "프리미엄 피자",
    line: "premium",
    title: "스페셜콰트로",
    price: "M 32,500 · L 39,500",
    pick: "네 가지 시그니처의 완벽한 밸런스",
    desc: "포테이토골드 · 쉬림프골드 · 콰트로치즈 · 스윗고구마를 한 판에 담은 미스터피자 대표 믹스.",
    tags: ["NEW", "SIGNATURE", "4 QUARTERS"],
    line: "premium",
    isBest: true,
    isBestCandidate: true,
    defaultEdge: "gold",
    allowedEdges: ["gold", "signature", "egg", "cream", "cheesecap"],
    originInfo: "미트토핑: 돼지고기(지방일부/국산), 쇠고기(호주산), 베이컨: 돼지고기(외국산)",
    nutritionInfo: {
      M: { kcal: 239, protein: 10, sodium: 394 },
      L: { kcal: 376, protein: 16, sodium: 630 },
    },
    allergyInfo: "난류, 우유, 대두, 밀, 새우, 돼지고기, 토마토, 쇠고기, 땅콩 함유",
  },
  {
    id: 2,
    img: "/mr-pizza/resources/images/component/menu/pizza-premium/pizza_premium_02.png",
    category: "프리미엄 피자",
    line: "premium",
    title: "미스터트리오",
    price: "M 32,500 · L 39,500",
    pick: "세 가지 시그니처의 완성형 조합",
    desc: "풍성한 토핑과 깊은 풍미가 어우러진 트리플 레이어. 고기, 치즈, 소스의 밸런스를 한 번에 즐기는 프리미엄 블렌드.",
    tags: ["TRIO", "PREMIUM", "BALANCED"],
    isBest: true,
    isBestCandidate: true,
    defaultEdge: "gold",
    allowedEdges: ["gold", "signature", "egg", "cream", "cheesecap"],
    originInfo: "미트토핑: 돼지고기(국산), 쇠고기(호주산), 치즈: 외국산",
    nutritionInfo: {
      M: { kcal: 243, protein: 13, sodium: 455 },
      L: { kcal: 322, protein: 17, sodium: 603 },
    },
    allergyInfo: "난류, 우유, 대두, 밀, 새우, 돼지고기, 토마토, 아황산류, 쇠고기, 조개류, 굴 함유",
  },
  {
    id: 3,
    img: "/mr-pizza/resources/images/component/menu/pizza-premium/pizza_premium_03.png",
    category: "프리미엄 피자",
    line: "premium",
    title: "치즈블라썸스테이크",
    price: "M 32,500 · L 39,500",
    pick: "꽃처럼 피어난 스테이크의 존재감",
    desc: "육즙 가득 스테이크와 치즈 블라썸이 만나 비주얼과 맛을 동시에 압도하는 시그니처.",
    tags: ["STEAK", "BLOSSOM", "SIGNATURE"],
    isBest: true,
    isBestCandidate: true,
    defaultEdge: "gold",
    allowedEdges: ["gold", "signature", "egg", "cream", "cheesecap"],
    originInfo: "스테이크: 쇠고기(호주산), 치즈: 외국산",
    nutritionInfo: {
      M: { kcal: 247, protein: 12, sodium: 397 },
      L: { kcal: 322, protein: 14, sodium: 524 },
    },
    allergyInfo: "난류, 우유, 대두, 밀, 새우, 돼지고기, 토마토, 아황산류, 소고기, 조개류, 굴 함유",
  },
  {
    id: 4,
    img: "/mr-pizza/resources/images/component/menu/pizza-classic/pizza_classic_01.png",
    category: "클래식 피자",
    line: "classic",
    title: "스윗고구마",
    price: "M 21,900 · L 28,900",
    pick: "달콤함이 먼저 오는 클래식",
    desc: "부드러운 고구마 무스와 크리미한 소스가 만들어내는 편안하고 깊은 단맛의 밸런스.",
    tags: ["SWEET", "CREAMY", "CLASSIC"],
    isSignature: true,
    defaultEdge: "origin",
    allowedEdges: ["origin", "signature", "cheesecap"],
    originInfo: "고구마무스: 국내산, 치즈: 외국산",
    nutritionInfo: {
      M: { kcal: 260, protein: 9, sodium: 410 },
      L: { kcal: 335, protein: 12, sodium: 550 },
    },
    allergyInfo: "난류, 우유, 대두, 땅콩, 밀, 돼지고기 함유",
  },
  {
    id: 5,
    img: "/mr-pizza/resources/images/component/menu/pizza-premium/pizza_premium_04.png",
    category: "프리미엄 피자",
    line: "premium",
    title: "디아볼라블라썸",
    price: "M 29,500 · L 36,500",
    pick: "부드러움 속 강렬한 반전",
    desc: "매콤한 살라미와 스파이시 소스가 치즈 블라썸과 어우러진 매혹적인 매운맛.",
    tags: ["SPICY", "SALAMI", "BLOSSOM"],
    defaultEdge: "gold",
    allowedEdges: ["gold", "signature", "egg", "cream", "cheesecap"],
    originInfo: "살라미: 돼지고기(국산), 쇠고기(호주산)",
    nutritionInfo: {
      M: { kcal: 278, protein: 12, sodium: 567 },
      L: { kcal: 365, protein: 16, sodium: 742 },
    },
    allergyInfo: "토마토, 우유, 대두, 돼지고기, 쇠고기, 달걀 함유",
  },
  {
    id: 6,
    img: "/mr-pizza/resources/images/component/menu/pizza-premium/pizza_premium_05.png",
    category: "프리미엄 피자",
    line: "premium",
    title: "레전드 포테이토",
    price: "M 31,500 · L 38,500",
    desc: "두툼한 감자와 달콤한 크림소스, 그리고 베이컨의 황금 밸런스. 클래식을 넘어선 ‘레전드’ 조합.",
    tags: ["POTATO", "CLASSIC HERO", "BEST SELLER"],
    defaultEdge: "gold",
    allowedEdges: ["gold", "signature", "egg", "cream", "cheesecap"],
    originInfo: "감자: 미국산, 베이컨: 돼지고기(외국산)",
    nutritionInfo: {
      M: { kcal: 312, protein: 13, sodium: 456 },
      L: { kcal: 403, protein: 18, sodium: 612 },
    },
    allergyInfo: "돼지고기, 대두, 우유, 계란, 밀, 쇠고기, 토마토 함유",
  },
  {
    id: 7,
    img: "/mr-pizza/resources/images/component/menu/pizza-classic/pizza_classic_02.png",
    category: "클래식 피자",
    line: "classic",
    title: "더블 치즈",
    price: "M 21,900 · L 28,900",
    pick: "치즈의 본질에 집중하다",
    desc: "두 배로 녹아내리는 치즈의 풍미. 불필요한 장식 없이 깊고 진한 고소함을 그대로 담은 클래식의 정석.",
    tags: ["CHEESE", "CLASSIC", "RICH"],
    isNew: true,
    defaultEdge: "origin",
    allowedEdges: ["origin", "signature", "cheesecap"],
    originInfo: "치즈: 외국산",
    nutritionInfo: {
      M: { kcal: 285, protein: 12, sodium: 420 },
      L: { kcal: 360, protein: 16, sodium: 570 },
    },
    allergyInfo: "난류, 우유, 대두, 밀, 토마토 함유",
  },
  {
    id: 8,
    img: "/mr-pizza/resources/images/component/menu/pizza-premium/pizza_premium_06.png",
    category: "프리미엄 피자",
    line: "premium",
    title: "쉬림프 골드",
    price: "M 32,500 · L 39,500",
    pick: "탱글한 쉬림프의 정석",
    desc: "버터 갈릭의 고소함과 풍성한 치즈가 어우러진 깊이 있는 프리미엄 씨푸드.",
    tags: ["BEST", "SEAFOOD", "BUTTER GARLIC"],
    isSignature: true,
    defaultEdge: "gold",
    allowedEdges: ["gold", "signature", "egg", "cream", "cheesecap"],
    originInfo: "새우: 베트남산, 치즈: 외국산",
    nutritionInfo: {
      M: { kcal: 265, protein: 16, sodium: 583 },
      L: { kcal: 401, protein: 21, sodium: 878 },
    },
    allergyInfo: "난류, 우유, 대두, 밀, 새우, 돼지고기, 토마토, 쇠고기 함유",
  },
  {
    id: 9,
    img: "/mr-pizza/resources/images/component/menu/pizza-premium/pizza_premium_07.png",
    category: "프리미엄 피자",
    line: "premium",
    title: "포테이토 골드",
    price: "M 31,500 · L 38,500",
    pick: "두툼한 감자의 정석, 변함없는 베스트",
    desc: "크리미한 감자무스와 고소한 베이컨, 달콤한 소스가 어우러진 미스터피자의 시그니처 클래식.",
    tags: ["BEST", "POTATO", "SIGNATURE"],
    isSignature: true,
    defaultEdge: "gold",
    allowedEdges: ["gold", "signature", "egg", "cream"],
    originInfo: "미트토핑: 돼지고기(지방일부/국산), 쇠고기(호주산), 베이컨: 돼지고기(외국산)",
    nutritionInfo: {
      M: { kcal: 245, protein: 11, sodium: 410 },
      L: { kcal: 372, protein: 17, sodium: 645 },
    },
    allergyInfo: "난류, 우유, 대두, 밀, 돼지고기, 토마토, 쇠고기 함유",
  },
  {
    id: 10,
    img: "/mr-pizza/resources/images/component/menu/pizza-premium/pizza_premium_08.png",
    category: "프리미엄 피자",
    line: "premium",
    title: "하프앤하프",
    price: "M 32,500 · L 39,500",
    pick: "두 가지 맛을 한 판에, 고민 끝내는 선택",
    desc: "취향이 다른 날에도 딱. 인기 토핑 조합을 반반으로 즐기는 실속형 프리미엄 믹스 피자.",
    tags: ["HALF & HALF", "MIX", "BEST PICK"],
    isSignature: true,
    defaultEdge: "gold",
    allowedEdges: ["gold", "signature", "egg", "cream", "cheesecap"],
    originInfo: "미트토핑: 돼지고기(지방일부/국산), 쇠고기(호주산), 베이컨:돼지고기(외국산)",
    nutritionInfo: {
      M: { kcal: 239, protein: 10, sodium: 394 },
      L: { kcal: 376, protein: 16, sodium: 630 },
    },
    allergyInfo: "난류, 우유, 대두, 밀, 새우, 돼지고기, 토마토, 쇠고기 함유",
  },
  {
    id: 11,
    img: "/mr-pizza/resources/images/component/menu/pizza-premium/pizza_premium_09.png",
    category: "프리미엄 피자",
    line: "premium",
    title: "크레이지 핫",
    price: "M 29,500 · L 36,500",
    pick: "맵단의 텐션을 끌어올리는 한 판",
    desc: "화끈한 스파이시 소스와 진한 치즈 밸런스. 한 입부터 끝까지 매력적으로 매운 프리미엄.",
    tags: ["SPICY", "BOLD", "HOT"],
    defaultEdge: "gold",
    allowedEdges: ["gold", "signature", "egg", "cream", "cheesecap"],
    originInfo: "미트토핑: 돼지고기(국산), 쇠고기(호주산)",
    nutritionInfo: {
      M: { kcal: 434, protein: 20, sodium: 869 },
      L: { kcal: 278, protein: 12, sodium: 567 },
    },
    allergyInfo: "밀, 토마토, 우유, 대두, 조개류(굴), 돼지고기, 쇠고기 함유",
  },
  {
    id: 12,
    img: "/mr-pizza/resources/images/component/menu/pizza-premium/pizza_premium_10.png",
    category: "프리미엄 피자",
    line: "premium",
    title: "콰트로 치즈",
    price: "M 30,500 · L 37,500",
    pick: "치즈의 결을 레이어로 즐기다",
    desc: "풍미가 다른 치즈가 겹겹이 녹아드는 클래식 프리미엄. 담백하면서도 깊은 치즈의 여운.",
    tags: ["CHEESE", "RICH", "CLASSIC"],
    defaultEdge: "gold",
    allowedEdges: ["gold", "signature", "egg", "cream", "cheesecap"],
    originInfo: "치즈: 외국산(모짜렐라, 체다 등)",
    nutritionInfo: {
      M: { kcal: 524, protein: 22, sodium: 830 },
      L: { kcal: 311, protein: 15, sodium: 526 },
    },
    allergyInfo: "밀, 토마토, 우유, 대두, 조개류(굴), 돼지고기, 쇠고기 함유",
  },
  {
    id: 13,
    img: "/mr-pizza/resources/images/component/menu/pizza-premium/pizza_premium_11.png",
    category: "프리미엄 피자",
    line: "premium",
    title: "레전드 바질 마스카포네",
    price: "M 29,500 · L 36,500",
    pick: "허브 향과 크리미함의 고급 조합",
    desc: "바질의 상큼한 향, 마스카포네의 부드러움. 깔끔한 풍미로 계속 손이 가는 프리미엄.",
    tags: ["BASIL", "MASCARPONE", "AROMATIC"],
    defaultEdge: "gold",
    allowedEdges: ["gold", "signature", "egg", "cream", "cheesecap"],
    originInfo: "치즈: 외국산, 바질: 수입산",
    nutritionInfo: {
      M: { kcal: 535, protein: 22, sodium: 671 },
      L: { kcal: 331, protein: 12, sodium: 414 },
    },
    allergyInfo: "토마토, 우유, 대두 함유",
  },
  {
    id: 14,
    img: "/mr-pizza/resources/images/component/menu/pizza-premium/pizza_premium_12.png",
    category: "프리미엄 피자",
    line: "premium",
    title: "레전드 쉬림프",
    price: "M 32,500 · L 39,500",
    pick: "탱글한 쉬림프, 확실한 존재감",
    desc: "바다의 감칠맛을 치즈와 소스로 꽉 채운 한 판. 씹을수록 고소하고 진한 씨푸드 무드.",
    tags: ["SEAFOOD", "SHRIMP", "BEST"],
    defaultEdge: "gold",
    allowedEdges: ["gold", "signature", "egg", "cream", "cheesecap"],
    originInfo: "새우: 베트남산, 치즈: 외국산",
    nutritionInfo: {
      M: { kcal: 474, protein: 21, sodium: 747 },
      L: { kcal: 309, protein: 14, sodium: 480 },
    },
    allergyInfo: "돼지고기, 대두, 우유, 계란, 밀, 쇠고기, 토마토, 새우 함유",
  },
  {
    id: 15,
    img: "/mr-pizza/resources/images/component/menu/pizza-premium/pizza_premium_13.png",
    category: "프리미엄 피자",
    line: "premium",
    title: "디아볼라 블라썸",
    price: "M 29,500 · L 36,500",
    pick: "부드러움 속 매콤한 반전",
    desc: "스파이시한 토핑과 소스가 치즈의 고소함을 끌어올리는 조합. 매운맛 입문부터 찐매운맛까지.",
    tags: ["SPICY", "SALAMI", "BLOSSOM"],
    defaultEdge: "gold",
    allowedEdges: ["gold", "signature", "egg", "cream", "cheesecap"],
    originInfo: "미트토핑: 돼지고기(국산), 쇠고기(호주산)",
    nutritionInfo: {
      M: { kcal: 490, protein: 24, sodium: 1002 },
      L: { kcal: 315, protein: 14, sodium: 492 },
    },
    allergyInfo: "토마토, 우유, 대두, 돼지고기, 쇠고기, 달걀 함유",
  },
  {
    id: 16,
    img: "/mr-pizza/resources/images/component/menu/pizza-premium/pizza_premium_14.png",
    category: "프리미엄 피자",
    line: "premium",
    title: "새우천왕",
    price: "M 32,500 · L 39,500",
    pick: "새우 토핑을 왕창, 이름값 하는 한 판",
    desc: "탱글한 새우와 감칠맛 토핑이 꽉 찬 씨푸드 프리미엄. 한 입마다 바삭·쫄깃·고소 밸런스.",
    tags: ["SEAFOOD", "SHRIMP", "KING"],
    defaultEdge: "gold",
    allowedEdges: ["gold", "signature", "egg", "cream", "cheesecap"],
    originInfo: "새우: 베트남산, 치즈: 외국산",
    nutritionInfo: {
      M: { kcal: 212, protein: 12, sodium: 449 },
      L: { kcal: 265, protein: 16, sodium: 583 },
    },
    allergyInfo: "난류, 우유, 대두, 밀, 새우, 돼지고기, 토마토, 아황산류, 쇠고기 함유",
  },
  // ---------- classic ----------
  {
    id: 17,
    img: "/mr-pizza/resources/images/component/menu/pizza-classic/pizza_classic_03.png",
    category: "클래식 피자",
    line: "classic",
    title: "콘 스노잉",
    price: "M 20,900 · L 27,900",
    pick: "달콤한 콘과 치즈의 포근한 조합",
    desc: "고소한 치즈 위에 콘 토핑을 듬뿍. 부담 없이 즐기기 좋은 데일리 클래식.",
    tags: ["CORN", "MILD", "CLASSIC"],
    defaultEdge: "origin",
    allowedEdges: ["origin", "signature", "cheesecap"],
    originInfo: "콘: 태국산, 치즈: 외국산",
    nutritionInfo: {
      M: { kcal: 255, protein: 11, sodium: 420 },
      L: { kcal: 330, protein: 14, sodium: 560 },
    },
    allergyInfo: "난류, 우유, 대두, 밀 함유",
  },
  {
    id: 18,
    img: "/mr-pizza/resources/images/component/menu/pizza-classic/pizza_classic_04.png",
    category: "클래식 피자",
    line: "classic",
    title: "치즈후라이",
    price: "M 21,900 · L 28,900",
    pick: "바삭한 감자와 치즈의 찐 조합",
    desc: "포테이토 토핑의 고소함과 치즈의 풍미가 딱 맞는 밸런스. 누구나 좋아하는 클래식.",
    tags: ["POTATO", "CHEESY", "COMFORT"],
    defaultEdge: "origin",
    allowedEdges: ["origin", "signature", "cheesecap"],
    originInfo: "감자: 미국산, 치즈: 외국산",
    nutritionInfo: {
      M: { kcal: 270, protein: 12, sodium: 450 },
      L: { kcal: 345, protein: 15, sodium: 590 },
    },
    allergyInfo: "우유, 대두, 밀, 토마토, 돼지고기 함유",
  },
  {
    id: 19,
    img: "/mr-pizza/resources/images/component/menu/pizza-classic/pizza_classic_05.png",
    category: "클래식 피자",
    line: "classic",
    title: "페퍼로니 플러스",
    price: "M 19,900 · L 26,900",
    pick: "짭짤한 페퍼로니의 정석",
    desc: "스파이시한 페퍼로니와 토마토 소스, 치즈가 만드는 클래식의 교과서. 실패 없는 선택.",
    tags: ["PEPPERONI", "CLASSIC", "BEST"],
    defaultEdge: "origin",
    allowedEdges: ["origin", "signature", "cheesecap"],
    originInfo: "페퍼로니: 돼지고기(국산), 쇠고기(호주산)",
    nutritionInfo: {
      M: { kcal: 290, protein: 13, sodium: 520 },
      L: { kcal: 365, protein: 17, sodium: 680 },
    },
    allergyInfo: "우유, 대두, 밀, 돼지고기, 토마토 함유",
  },
  {
    id: 20,
    img: "/mr-pizza/resources/images/component/menu/pizza-classic/pizza_classic_06.png",
    category: "클래식 피자",
    line: "classic",
    title: "베지테리안",
    price: "M 19,900 · L 26,900",
    pick: "가볍고 산뜻하게 즐기는 한 판",
    desc: "신선한 채소 토핑의 아삭함과 담백한 치즈 밸런스. 부담 없이 깔끔하게 즐기기 좋아.",
    tags: ["VEGGIE", "FRESH", "LIGHT"],
    defaultEdge: "origin",
    allowedEdges: ["origin", "signature", "cheesecap"],
    originInfo: "채소믹스: 국내산·수입산 혼합",
    nutritionInfo: {
      M: { kcal: 220, protein: 9, sodium: 350 },
      L: { kcal: 300, protein: 12, sodium: 480 },
    },
    allergyInfo: "우유, 대두, 밀, 토마토 함유",
  },
  {
    id: 21,
    img: "/mr-pizza/resources/images/component/menu/pizza-classic/pizza_classic_07.png",
    category: "클래식 피자",
    line: "classic",
    title: "하와이안스페셜",
    price: "M 20,900 · L 27,900",
    pick: "달콤-짭짤 조합의 원조",
    desc: "파인애플의 달콤함과 햄/치즈의 짭짤함이 만드는 중독적인 밸런스. 호불호 있어도 계속 생각나.",
    tags: ["HAWAIIAN", "SWEET & SALTY", "TROPICAL"],
    defaultEdge: "origin",
    allowedEdges: ["origin", "signature", "cheesecap"],
    originInfo: "햄: 돼지고기(국산), 파인애플: 필리핀산",
    nutritionInfo: {
      M: { kcal: 275, protein: 12, sodium: 480 },
      L: { kcal: 350, protein: 16, sodium: 640 },
    },
    allergyInfo: "난류, 우유, 대두, 밀, 돼지고기, 토마토, 굴 함유",
  },
  {
    id: 22,
    img: "/mr-pizza/resources/images/component/menu/pizza-classic/pizza_classic_08.png",
    category: "클래식 피자",
    line: "classic",
    title: "콤비네이션",
    price: "M 21,900 · L 28,900",
    pick: "토핑 밸런스가 완벽한 올라운더",
    desc: "고기+야채+치즈가 고루 들어간 기본 중의 기본. 처음 주문할 때 가장 안전한 선택.",
    tags: ["BALANCED", "ALL-ROUNDER", "CLASSIC"],
    defaultEdge: "origin",
    allowedEdges: ["origin", "signature", "cheesecap"],
    originInfo: "햄: 돼지고기(국산), 쇠고기: 호주산",
    nutritionInfo: {
      M: { kcal: 285, protein: 14, sodium: 520 },
      L: { kcal: 360, protein: 18, sodium: 690 },
    },
    allergyInfo: "난류, 우유, 대두, 밀, 돼지고기, 토마토, 쇠고기 함유",
  },
  {
    id: 23,
    img: "/mr-pizza/resources/images/component/menu/pizza-classic/pizza_classic_09.png",
    category: "클래식 피자",
    line: "classic",
    title: "포테이토",
    price: "M 21,900 · L 28,900",
    pick: "담백한 감자의 고소함 한가득",
    desc: "두툼한 감자 토핑과 크리미한 소스가 어우러지는 스테디셀러. 부드럽고 편안한 맛.",
    tags: ["POTATO", "MILD", "BEST"],
    defaultEdge: "origin",
    allowedEdges: ["origin", "cheesecap"],
    originInfo: "감자: 미국산, 치즈: 외국산",
    nutritionInfo: {
      M: { kcal: 265, protein: 11, sodium: 430 },
      L: { kcal: 340, protein: 14, sodium: 570 },
    },
    allergyInfo: "난류, 우유, 대두, 밀, 돼지고기, 토마토, 쇠고기 함유",
  },
  {
    id: 24,
    img: "/mr-pizza/resources/images/component/menu/pizza-classic/pizza_classic_10.png",
    category: "클래식 피자",
    line: "classic",
    title: "불고기",
    price: "M 21,900 · L 28,900",
    pick: "달달한 불고기 소스의 한국식 클래식",
    desc: "짭짤달콤한 불고기 토핑과 치즈가 만나 남녀노소 모두 좋아하는 한 판.",
    tags: ["BULGOGI", "SWEET", "K-CLASSIC"],
    defaultEdge: "origin",
    allowedEdges: ["origin", "signature", "cheesecap"],
    originInfo: "불고기: 쇠고기(호주산)",
    nutritionInfo: {
      M: { kcal: 300, protein: 15, sodium: 580 },
      L: { kcal: 380, protein: 19, sodium: 730 },
    },
    allergyInfo: "우유, 대두, 밀, 돼지고기, 토마토, 쇠고기 함유",
  },
  {
    id: 25,
    img: "/mr-pizza/resources/images/component/menu/pizza-classic/pizza_classic_11.png",
    category: "클래식 피자",
    line: "classic",
    title: "시카고딥",
    price: "M 25,900 · L 31,900",
    pick: "두툼한 치즈 레이어의 딥한 만족감",
    desc: "치즈를 꽉 채운 딥디쉬 스타일. 한 조각만으로도 든든한, 진짜 ‘한 끼’ 같은 피자.",
    tags: ["DEEP DISH", "HEAVY", "CHEESY"],
    defaultEdge: "noedge",
    allowedEdges: ["noedge"],
    edgeLocked: true,
    originInfo: "치즈: 외국산",
    nutritionInfo: {
      M: { kcal: 420, protein: 18, sodium: 700 },
      L: { kcal: 510, protein: 23, sodium: 880 },
    },
    allergyInfo: "난류, 우유, 대두, 밀, 돼지고기, 토마토, 쇠고기 함유",
  },
  // ---------- suncrust ----------
  {
    id: 26,
    img: "/mr-pizza/resources/images/component/menu/pizza-suncrust/pizza_suncrust_01.png",
    category: "씬크러스트 피자",
    line: "suncrust",
    title: "더블치즈(씬)",
    price: "M 21,900 · L 28,900",
    pick: "얇은 도우 위 진한 치즈의 직관적인 풍미",
    desc: "도우는 가볍게, 치즈는 두 배로. 씬 특유의 바삭함과 고소함이 살아있는 심플 클래식.",
    tags: ["THIN", "CHEESE", "LIGHT"],
    originInfo: "치즈: 외국산",
    nutritionInfo: {
      M: { kcal: 235, protein: 11, sodium: 390 },
      L: { kcal: 310, protein: 15, sodium: 520 },
    },
    allergyInfo: "난류, 우유, 대두, 밀, 토마토 함유",
  },
  {
    id: 27,
    img: "/mr-pizza/resources/images/component/menu/pizza-suncrust/pizza_suncrust_02.png",
    category: "씬크러스트 피자",
    line: "suncrust",
    title: "콘스노잉(씬)",
    price: "M 20,900 · L 27,900",
    pick: "달콤한 콘의 고소한 한 판",
    desc: "옥수수의 달콤함과 치즈의 고소함이 가볍게 어우러진 씬크러스트.",
    tags: ["CORN", "SWEET", "LIGHT"],
    originInfo: "",
    nutritionInfo: {
      M: { kcal: 235, protein: 10, sodium: 380 },
      L: { kcal: 310, protein: 13, sodium: 510 },
    },
    allergyInfo: "난류, 우유, 대두, 밀 함유",
  },
  {
    id: 28,
    img: "/mr-pizza/resources/images/component/menu/pizza-suncrust/pizza_suncrust_03.png",
    category: "씬크러스트 피자",
    line: "suncrust",
    title: "치즈후라이(씬)",
    price: "M 21,900 · L 28,900",
    pick: "치즈와 감자의 중독 조합",
    desc: "고소한 치즈와 감자 토핑에 베이컨 풍미가 더해진 씬 피자.",
    tags: ["CHEESE", "POTATO", "RICH"],
    originInfo: "베이컨 : 돼지고기(외국산)",
    nutritionInfo: {
      M: { kcal: 255, protein: 11, sodium: 420 },
      L: { kcal: 330, protein: 14, sodium: 560 },
    },
    allergyInfo: "우유, 대두, 밀, 토마토, 돼지고기 함유",
  },
  {
    id: 29,
    img: "/mr-pizza/resources/images/component/menu/pizza-suncrust/pizza_suncrust_04.png",
    category: "씬크러스트 피자",
    line: "suncrust",
    title: "페퍼로니플러스(씬)",
    price: "M 19,900 · L 26,900",
    pick: "짭짤한 페퍼로니의 정석",
    desc: "스파이시 페퍼로니와 치즈가 어우러진 클래식 스타일.",
    tags: ["PEPPERONI", "CLASSIC", "BEST"],
    originInfo: "페퍼로니 : 돼지고기(국산)",
    nutritionInfo: {
      M: { kcal: 245, protein: 12, sodium: 430 },
      L: { kcal: 320, protein: 15, sodium: 580 },
    },
    allergyInfo: "우유, 대두, 밀, 돼지고기, 토마토함유",
  },
  {
    id: 30,
    img: "/mr-pizza/resources/images/component/menu/pizza-suncrust/pizza_suncrust_05.png",
    category: "씬크러스트 피자",
    line: "suncrust",
    title: "베지테리안(씬)",
    price: "M 19,900 · L 26,900",
    pick: "가볍고 산뜻한 선택",
    desc: "신선한 채소 토핑이 조화를 이루는 담백한 씬 피자.",
    tags: ["VEGGIE", "FRESH", "LIGHT"],
    originInfo: "",
    nutritionInfo: {
      M: { kcal: 220, protein: 9, sodium: 350 },
      L: { kcal: 295, protein: 12, sodium: 470 },
    },
    allergyInfo: "우유, 대두, 밀, 토마토 함유",
  },
  {
    id: 31,
    img: "/mr-pizza/resources/images/component/menu/pizza-suncrust/pizza_suncrust_06.png",
    category: "씬크러스트 피자",
    line: "suncrust",
    title: "하와이안스페셜(씬)",
    price: "M 20,900 · L 27,900",
    pick: "달콤짭짤 하와이안",
    desc: "파인애플과 햄이 어우러진 달콤짭짤한 인기 조합.",
    tags: ["HAWAIIAN", "SWEET", "TROPICAL"],
    originInfo: "카나디안햄 : 돼지고기(국내산과 외국산 섞음)",
    nutritionInfo: {
      M: { kcal: 240, protein: 11, sodium: 410 },
      L: { kcal: 315, protein: 14, sodium: 550 },
    },
    allergyInfo: "난류, 우유, 대두, 밀, 돼지고기, 토마토, 굴 함유",
  },
  {
    id: 32,
    img: "/mr-pizza/resources/images/component/menu/pizza-suncrust/pizza_suncrust_07.png",
    category: "씬크러스트 피자",
    line: "suncrust",
    title: "콤비네이션(씬)",
    price: "M 21,900 · L 28,900",
    pick: "토핑 밸런스의 정석",
    desc: "미트와 채소가 균형 잡힌 클래식 콤비네이션.",
    tags: ["BALANCED", "CLASSIC", "MEAT"],
    originInfo: "미트토핑: 돼지고기(지방일부/국산), 쇠고기(호주산), 페퍼로니: 돼지고기(국산), 카나디안햄: 돼지고기(국내산과 외국산 섞음), 베이컨: 돼지고기(외국산)",
    nutritionInfo: {
      M: { kcal: 260, protein: 13, sodium: 450 },
      L: { kcal: 335, protein: 17, sodium: 600 },
    },
    allergyInfo: "난류, 우유, 대두, 밀, 돼지고기, 토마토, 쇠고기 함유",
  },
  {
    id: 33,
    img: "/mr-pizza/resources/images/component/menu/pizza-suncrust/pizza_suncrust_08.png",
    category: "씬크러스트 피자",
    line: "suncrust",
    title: "포테이토(씬)",
    price: "M 21,900 · L 28,900",
    pick: "부드러운 감자 토핑",
    desc: "고소한 감자와 베이컨이 어우러진 인기 메뉴.",
    tags: ["POTATO", "CREAMY", "BEST"],
    originInfo: "미트토핑: 돼지고기(지방일부/국산), 쇠고기(호주산), 베이컨: 돼지고기(외국산)",
    nutritionInfo: {
      M: { kcal: 265, protein: 12, sodium: 440 },
      L: { kcal: 340, protein: 16, sodium: 590 },
    },
    allergyInfo: "난류, 우유, 대두, 밀, 돼지고기, 토마토, 쇠고기 함유",
  },
  {
    id: 34,
    img: "/mr-pizza/resources/images/component/menu/pizza-suncrust/pizza_suncrust_09.png",
    category: "씬크러스트 피자",
    line: "suncrust",
    title: "불고기(씬)",
    price: "M 21,900 · L 28,900",
    pick: "달콤한 불고기 풍미",
    desc: "달콤짭짤 불고기 소스와 치즈가 어우러진 한국식 피자.",
    tags: ["BULGOGI", "KOREAN", "SWEET"],
    originInfo: "소불고기 : 쇠고기(호주산)",
    nutritionInfo: {
      M: { kcal: 270, protein: 13, sodium: 470 },
      L: { kcal: 350, protein: 17, sodium: 620 },
    },
    allergyInfo: "우유, 대두, 밀, 돼지고기, 토마토, 쇠고기 함유",
  },
  {
    id: 35,
    img: "/mr-pizza/resources/images/component/menu/pizza-suncrust/pizza_suncrust_10.png",
    category: "씬크러스트 피자",
    line: "suncrust",
    title: "스윗고구마(씬)",
    price: "M 21,900 · L 28,900",
    pick: "달콤한 고구마 인기픽",
    desc: "달콤한 고구마 무스와 베이컨의 단짠 조합.",
    tags: ["SWEET", "POTATO", "BEST"],
    originInfo: "베이컨 : 돼지고기(외국산)",
    nutritionInfo: {
      M: { kcal: 275, protein: 11, sodium: 430 },
      L: { kcal: 355, protein: 15, sodium: 590 },
    },
    allergyInfo: "난류, 우유, 대두, 땅콩, 밀, 돼지고기 함유",
  },
  // ---------- solo ----------
  {
    id: 37,
    img: "/mr-pizza/resources/images/component/menu/pizza-solo/pizza_solo_01.png",
    category: "1인용 피자",
    line: "solo",
    title: "페퍼로니플러스(S)",
    price: "S 8,900",
    pick: "혼자서도 제대로 즐기는 페퍼로니 클래식",
    desc: "스파이시한 페퍼로니와 치즈의 정석 조합. 부담 없이 한 판을 즐기기 좋은 1인 사이즈.",
    tags: ["SOLO", "PEPPERONI", "BEST"],
    originInfo: "페퍼로니: 돼지고기(국산), 쇠고기(호주산)",
    nutritionInfo: {
      S: { kcal: 685, protein: 28, sodium: 1150 },
    },
    allergyInfo: "난류, 우유, 대두, 밀, 돼지고기, 쇠고기, 토마토 함유",
  },
  {
    id: 38,
    img: "/mr-pizza/resources/images/component/menu/pizza-solo/pizza_solo_02.png",
    category: "1인용 피자",
    line: "solo",
    title: "콤비네이션(S)",
    price: "S 10,900",
    pick: "토핑 밸런스 완벽한 1인 올라운더",
    desc: "미트+야채+치즈가 고루 들어간 기본 중의 기본. 혼자 먹어도 ‘한 판 만족’ 확실한 조합.",
    tags: ["SOLO", "COMBI", "BALANCED"],
    originInfo: "미트토핑: 돼지고기(지방일부/국산), 쇠고기(호주산), 페퍼로니: 돼지고기(국산), 카나디안햄: 돼지고기(국내산과 외국산 섞음), 베이컨: 돼지고기(외국산)",
    nutritionInfo: {
      S: { kcal: 720, protein: 30, sodium: 1280 },
    },
    allergyInfo: "난류, 우유, 대두, 밀, 돼지고기, 토마토, 쇠고기 함유",
  },
  {
    id: 39,
    img: "/mr-pizza/resources/images/component/menu/pizza-solo/pizza_solo_03.png",
    category: "1인용 피자",
    line: "solo",
    title: "불고기(S)",
    price: "S 10,900",
    pick: "달짝지근 불고기 풍미를 한 판에",
    desc: "불고기의 달콤짭짤한 풍미와 치즈가 어우러진 K-스테디셀러. 얇고 가볍게 즐겨도 만족감은 든든해.",
    tags: ["SOLO", "BULGOGI", "KOREAN"],
    originInfo: "소불고기 : 쇠고기(호주산)",
    nutritionInfo: {
      S: { kcal: 735, protein: 31, sodium: 1320 },
    },
    allergyInfo: "우유, 대두, 밀, 돼지고기, 토마토, 쇠고기 함유",
  },
  {
    id: 40,
    img: "/mr-pizza/resources/images/component/menu/pizza-solo/pizza_solo_04.png",
    category: "1인용 피자",
    line: "solo",
    title: "스윗고구마(S)",
    price: "S 10,900",
    pick: "달콤한 고구마 무스, 단짠의 정답",
    desc: "달콤한 고구마 무스에 베이컨의 짭짤함이 더해진 단짠 밸런스. 디저트처럼 부드럽게 들어가.",
    tags: ["SOLO", "SWEETPOTATO", "BEST"],
    originInfo: "베이컨 : 돼지고기(외국산)",
    nutritionInfo: {
      S: { kcal: 760, protein: 27, sodium: 1180 },
    },
    allergyInfo: "난류, 우유, 대두, 땅콩, 밀, 돼지고기 함유",
  },
  {
    id: 41,
    img: "/mr-pizza/resources/images/component/menu/pizza-solo/pizza_solo_05.png",
    category: "1인용 피자",
    line: "solo",
    title: "하와이안스페셜(S)",
    price: "S 9,900",
    pick: "달콤-짭짤 하와이안 한 판",
    desc: "파인애플의 달콤함과 햄/치즈의 짭짤함이 만드는 중독적인 조합. 혼자 먹기 딱 좋은 사이즈로 가볍게!",
    tags: ["SOLO", "HAWAIIAN", "SWEET & SALTY"],
    originInfo: "카나디안햄 : 돼지고기(국내산과 외국산 섞음)",
    nutritionInfo: {
      S: { kcal: 700, protein: 28, sodium: 1200 },
    },
    allergyInfo: "난류, 우유, 대두, 밀, 돼지고기, 토마토, 굴 함유",
  },
  {
    id: 42,
    img: "/mr-pizza/resources/images/component/menu/pizza-solo/pizza_solo_06.png",
    category: "1인용 피자",
    line: "solo",
    title: "베지테리안(S)",
    price: "S 9,900",
    pick: "가볍고 산뜻하게 즐기는 1인 픽",
    desc: "신선한 채소 토핑의 아삭함과 담백한 치즈 밸런스. 부담 없이 깔끔하게 즐기기 좋아.",
    tags: ["SOLO", "VEGGIE", "LIGHT"],
    originInfo: "",
    nutritionInfo: {
      S: { kcal: 640, protein: 24, sodium: 980 },
    },
    allergyInfo: "우유, 대두, 밀, 토마토 함유",
  },

  // ---------- sand ----------
  {
    id: 43,
    img: "/mr-pizza/resources/images/component/menu/pizza-sand/pizza_sand_01.png",
    category: "피자샌드",
    line: "pizzasand",
    title: "콤비네이션 샌드",
    price: "6,900",
    pick: "피자의 맛을 간편하게 즐기는 한 입 샌드",
    desc: "콤비네이션 토핑을 바삭한 브레드 사이에 담아낸 스낵형 메뉴. 가볍지만 만족감은 충분해.",
    tags: ["SNACK", "COMBI", "LIGHT"],
    isNew: true,
    originInfo: "햄: 돼지고기(국산), 쇠고기(호주산)",
    nutritionInfo: {
      kcal: 420,
      protein: 14,
      sodium: 780,
    },
    allergyInfo: "난류, 우유, 대두, 밀, 돼지고기, 쇠고기 함유",
  },
  {
    id: 44,
    img: "/mr-pizza/resources/images/component/menu/pizza-sand/pizza_sand_02.png",
    category: "피자샌드",
    line: "pizzasand",
    title: "치킨텐더 샌드",
    price: "6,900",
    pick: "겉바속촉 치킨텐더로 든든하게",
    desc: "바삭한 치킨텐더와 치즈/소스 조합을 브레드에 꽉. 간편하게 먹어도 단백질 만족감 좋은 스낵.",
    tags: ["CHICKEN", "SNACK", "PROTEIN"],
    isNew: true,
    originInfo: "치킨텐더: 닭고기(국내산)",
    nutritionInfo: {
      kcal: 450,
      protein: 18,
      sodium: 820,
    },
    allergyInfo: "닭고기, 대두, 밀, 달걀, 쇠고기, 난류, 우유 함유",
  },
  {
    id: 45,
    img: "/mr-pizza/resources/images/component/menu/pizza-sand/pizza_sand_03.png",
    category: "피자샌드",
    line: "pizzasand",
    title: "소세지 샌드",
    price: "6,900",
    pick: "육즙 팡팡 소세지 한 입",
    desc: "부어스트 소세지의 풍미를 브레드에 담아 한 입에. 짭짤하고 고소해서 간식/맥주 안주로도 찰떡.",
    tags: ["SAUSAGE", "SNACK", "SAVORY"],
    isNew: true,
    originInfo: "소세지(부어스트): 돼지고기(지방일부/국산)",
    nutritionInfo: {
      kcal: 470,
      protein: 16,
      sodium: 900,
    },
    allergyInfo: "난류, 우유, 대두, 밀, 돼지고기 함유",
  },
  {
    id: 46,
    img: "/mr-pizza/resources/images/component/menu/pizza-sand/pizza_sand_04.png",
    category: "피자샌드",
    line: "pizzasand",
    title: "불고기 샌드",
    price: "6,900",
    pick: "달콤불고기 풍미를 간편하게",
    desc: "달짝지근한 불고기 토핑을 치즈와 함께 샌드로. 부담 없이 즐기는 K-스낵 메뉴.",
    tags: ["BULGOGI", "SNACK", "KOREAN"],
    originInfo: "소불고기 : 쇠고기(호주산)",
    nutritionInfo: {
      kcal: 455,
      protein: 17,
      sodium: 840,
    },
    allergyInfo: "난류, 우유, 대두, 밀, 쇠고기 함유",
  },
  {
    id: 47,
    img: "/mr-pizza/resources/images/component/menu/pizza-sand/pizza_sand_05.png",
    category: "피자샌드",
    line: "pizzasand",
    title: "포테이토골드 샌드",
    price: "6,900",
    pick: "고소한 포테이토를 한 입에",
    desc: "포슬한 감자 토핑과 치즈의 고소함을 바삭한 브레드로. 가볍게 먹기 좋은 스테디 스낵.",
    tags: ["POTATO", "SNACK", "RICH"],
    originInfo: "미트토핑: 돼지고기(지방일부/국산), 쇠고기(호주산), 베이컨: 돼지고기(외국산)",
    nutritionInfo: {
      kcal: 440,
      protein: 15,
      sodium: 820,
    },
    allergyInfo: "난류, 우유, 대두, 밀, 돼지고기, 토마토, 쇠고기 함유",
  },
  {
    id: 48,
    img: "/mr-pizza/resources/images/component/menu/pizza-sand/pizza_sand_06.png",
    category: "피자샌드",
    line: "pizzasand",
    title: "쉬림프골드 샌드",
    price: "6,900",
    pick: "새우의 감칠맛이 확 살아나는 샌드",
    desc: "탱글한 새우 풍미에 고소한 치즈가 더해진 샌드. 한 입으로도 바다향 감칠맛 제대로.",
    tags: ["SHRIMP", "SNACK", "UMAMI"],
    originInfo: "미트토핑: 돼지고기(지방일부/국산), 쇠고기(호주산), 베이컨: 돼지고기(외국산)",
    nutritionInfo: {
      kcal: 430,
      protein: 16,
      sodium: 860,
    },
    allergyInfo: "난류, 우유, 대두, 밀, 새우, 돼지고기, 토마토, 쇠고기 함유",
  },
  // ---------- sand set ----------
  {
    id: 49,
    img: "/mr-pizza/resources/images/component/menu/pizza-sand/pizza_sand_07.png",
    category: "피자샌드",
    line: "pizzasand",
    title: "콤비네이션 샌드 세트",
    price: "9,500",
    pick: "한 입 샌드+사이드+음료로 딱",
    desc: `콤비네이션 토핑을 바삭한 브레드 사이에 담아낸 스낵형 메뉴.
가볍지만 만족감은 충분해.

※ 세트구성 : 콤비네이션 샌드 + 스파이시포테이토 + 콜라(245ml)
※ 포테이토/음료 영양정보는 사이드 메뉴에서 확인 가능합니다.`,
    tags: ["SET", "SNACK", "COMBI"],
    isNew: true,
    originInfo: "햄: 돼지고기(국산), 쇠고기(호주산)",
    nutritionInfo: {
      kcal: 420,
      protein: 14,
      sodium: 780,
    },
    allergyInfo: "난류, 우유, 대두, 밀, 돼지고기, 쇠고기 함유",
  },
  {
    id: 50,
    img: "/mr-pizza/resources/images/component/menu/pizza-sand/pizza_sand_08.png",
    category: "피자샌드",
    line: "pizzasand",
    title: "치킨텐더 샌드 세트",
    price: "9,500",
    pick: "바삭한 치킨텐더로 든든하게",
    desc: `바삭한 치킨텐더와 치즈/소스 조합을 브레드에 꽉 담은 스낵 메뉴.
간편하게 먹어도 단백질 만족감 좋은 메뉴야.

※ 세트구성 : 치킨텐더 샌드 + 스파이시포테이토 + 콜라(245ml)
※ 포테이토/음료 영양정보는 사이드 메뉴에서 확인 가능합니다.`,
    tags: ["SET", "CHICKEN", "PROTEIN"],
    isNew: true,
    originInfo: "치킨텐더: 닭고기(국내산)",
    nutritionInfo: {
      kcal: 450,
      protein: 18,
      sodium: 820,
    },
    allergyInfo: "닭고기, 대두, 밀, 달걀, 쇠고기, 난류, 우유 함유",
  },
  {
    id: 51,
    img: "/mr-pizza/resources/images/component/menu/pizza-sand/pizza_sand_09.png",
    category: "피자샌드",
    line: "pizzasand",
    title: "소세지 샌드 세트",
    price: "9,500",
    pick: "육즙 소세지로 진하게",
    desc: `부어스트 소세지의 풍미를 브레드에 담아 한 입에 즐기는 샌드.
짭짤하고 고소해서 간식이나 가벼운 식사로도 좋아.

※ 세트구성 : 소세지 샌드 + 스파이시포테이토 + 콜라(245ml)
※ 포테이토/음료 영양정보는 사이드 메뉴에서 확인 가능합니다.`,
    tags: ["SET", "SAUSAGE", "SAVORY"],
    isNew: true,
    originInfo: "소세지(부어스트): 돼지고기(지방일부/국산)",
    nutritionInfo: {
      kcal: 470,
      protein: 16,
      sodium: 900,
    },
    allergyInfo: "난류, 우유, 대두, 밀, 돼지고기 함유",
  },
  {
    id: 52,
    img: "/mr-pizza/resources/images/component/menu/pizza-sand/pizza_sand_10.png",
    category: "피자샌드",
    line: "pizzasand",
    title: "불고기 샌드 세트",
    price: "9,500",
    pick: "달콤불고기 K-스낵",
    desc: `달짝지근한 불고기 토핑을 치즈와 함께 샌드로 담은 메뉴.
부담 없이 즐길 수 있는 K-스타일 스낵.

※ 세트구성 : 불고기 샌드 + 스파이시포테이토 + 콜라(245ml)
※ 포테이토/음료 영양정보는 사이드 메뉴에서 확인 가능합니다.`,
    tags: ["SET", "BULGOGI", "KOREAN"],
    originInfo: "소불고기 : 쇠고기(호주산)",
    nutritionInfo: {
      kcal: 455,
      protein: 17,
      sodium: 840,
    },
    allergyInfo: "난류, 우유, 대두, 밀, 쇠고기 함유",
  },
  {
    id: 53,
    img: "/mr-pizza/resources/images/component/menu/pizza-sand/pizza_sand_11.png",
    category: "피자샌드",
    line: "pizzasand",
    title: "포테이토골드 샌드 세트",
    price: "9,500",
    pick: "고소한 포테이토+치즈 조합",
    desc: `포슬한 감자 토핑과 치즈의 고소함을 브레드에 담은 메뉴.
부담 없이 즐기기 좋은 스테디 스낵.

※ 세트구성 : 포테이토골드 샌드 + 스파이시포테이토 + 콜라(245ml)
※ 포테이토/음료 영양정보는 사이드 메뉴에서 확인 가능합니다.`,
    tags: ["SET", "POTATO", "RICH"],
    originInfo: "미트토핑: 돼지고기(지방일부/국산), 쇠고기(호주산), 베이컨: 돼지고기(외국산)",
    nutritionInfo: {
      kcal: 440,
      protein: 15,
      sodium: 820,
    },
    allergyInfo: "난류, 우유, 대두, 밀, 돼지고기, 토마토, 쇠고기 함유",
  },
  {
    id: 54,
    img: "/mr-pizza/resources/images/component/menu/pizza-sand/pizza_sand_12.png",
    category: "피자샌드",
    line: "pizzasand",
    title: "쉬림프골드 샌드 세트",
    price: "9,500",
    pick: "탱글 새우 풍미 한 입",
    desc: `탱글한 새우 풍미에 고소한 치즈가 더해진 샌드.
한 입으로도 바다향 감칠맛을 느낄 수 있어.

※ 세트구성 : 쉬림프골드 샌드 + 스파이시포테이토 + 콜라(245ml)
※ 포테이토/음료 영양정보는 사이드 메뉴에서 확인 가능합니다.`,
    tags: ["SET", "SHRIMP", "UMAMI"],
    originInfo: "미트토핑: 돼지고기(지방일부/국산), 쇠고기(호주산), 베이컨: 돼지고기(외국산)",
    nutritionInfo: {
      kcal: 430,
      protein: 16,
      sodium: 860,
    },
    allergyInfo: "난류, 우유, 대두, 밀, 새우, 돼지고기, 토마토, 쇠고기 함유",
  },
  // ---------- pasta-rice ----------
  {
    id: 55,
    img: "/mr-pizza/resources/images/component/menu/pasta-rice/pasta_rice_01.png",
    category: "파스타&라이스",
    line: "pasta",
    title: "불고기 라이스",
    price: "9,900",
    pick: "달콤짭짤 불고기와 치즈의 든든한 한 그릇",
    desc: "한국식 불고기 소스와 고소한 치즈가 어우러진 라이스 메뉴. 한 끼 식사로 충분해.",
    tags: ["RICE", "BULGOGI", "MEAL"],
    isNew: true,
    originInfo: "불고기: 쇠고기(호주산)",
    nutritionInfo: {
      kcal: 680,
      protein: 25,
      sodium: 1050,
    },
    allergyInfo: "난류, 우유, 대두, 밀, 쇠고기 함유",
  },
  {
    id: 56,
    img: "/mr-pizza/resources/images/component/menu/pasta-rice/pasta_rice_02.png",
    category: "파스타&라이스",
    line: "pasta",
    title: "바질크림파스타",
    price: "9,900",
    pick: "바질 향과 크림의 부드러운 조화",
    desc: "향긋한 바질페스토와 진한 크림소스가 어우러진 파스타. 베이컨이 더해져 풍미가 한층 진해.",
    tags: ["PASTA", "BASIL", "CREAM"],
    isNew: true,
    originInfo: "바질페스토: 바질(스페인산), 베이컨: 돼지고기(외국산)",
    nutritionInfo: {
      kcal: 720,
      protein: 23,
      sodium: 1180,
    },
    allergyInfo: "난류, 우유, 대두, 밀, 돼지고기, 닭고기, 쇠고기, 토마토 함유",
  },
  {
    id: 57,
    img: "/mr-pizza/resources/images/component/menu/pasta-rice/pasta_rice_03.png",
    category: "파스타&라이스",
    line: "pasta",
    title: "오븐치즈 미트 스파게티",
    price: "8,900",
    pick: "치즈와 미트소스의 클래식 조합",
    desc: "진한 미트소스 스파게티를 오븐에 한 번 더 구워 치즈 풍미를 살린 메뉴. 호불호 없이 든든한 맛.",
    tags: ["PASTA", "MEAT", "CHEESE"],
    isSignature: true,
    originInfo: "미트소스: 돼지고기(국내산), 쇠고기(호주산)",
    nutritionInfo: {
      kcal: 690,
      protein: 24,
      sodium: 1120,
    },
    allergyInfo: "우유, 대두, 밀, 돼지고기, 토마토, 닭고기, 쇠고기 함유",
  },
  {
    id: 58,
    img: "/mr-pizza/resources/images/component/menu/pasta-rice/pasta_rice_04.png",
    category: "파스타&라이스",
    line: "pasta",
    title: "오븐치즈 베이컨크림 스파게티",
    price: "8,900",
    pick: "꾸덕한 크림과 베이컨의 정석",
    desc: "고소한 크림소스에 베이컨을 더하고 오븐치즈로 마무리한 스파게티. 부드럽고 진한 맛이 특징이야.",
    tags: ["PASTA", "BACON", "CREAM"],
    originInfo: "베이컨: 돼지고기(외국산)",
    nutritionInfo: {
      kcal: 740,
      protein: 22,
      sodium: 1160,
    },
    allergyInfo: "난류, 우유, 대두, 밀, 돼지고기 함유",
  },
  {
    id: 59,
    img: "/mr-pizza/resources/images/component/menu/pasta-rice/pasta_rice_05.png",
    category: "파스타&라이스",
    line: "pasta",
    title: "쉬림프 까르보나라",
    price: "9,900",
    pick: "새우와 크림의 부드러운 인기 조합",
    desc: "탱글한 새우와 고소한 까르보나라 소스가 어우러진 파스타. 진하지만 부담 없이 즐기기 좋아.",
    tags: ["PASTA", "SHRIMP", "CARBONARA"],
    originInfo: "베이컨: 돼지고기(외국산)",
    nutritionInfo: {
      kcal: 735,
      protein: 26,
      sodium: 1190,
    },
    allergyInfo: "난류, 우유, 대두, 밀, 새우, 돼지고기, 닭고기, 쇠고기 함유",
  },
  {
    id: 60,
    img: "/mr-pizza/resources/images/component/menu/pasta-rice/pasta_rice_06.png",
    category: "파스타&라이스",
    line: "pasta",
    title: "쉬림프 로제 파스타",
    price: "9,900",
    pick: "로제 소스에 새우를 더한 부드러운 한 접시",
    desc: "크림과 토마토가 조화로운 로제소스에 새우를 더해 감칠맛을 살린 파스타. 무난하게 인기 많은 메뉴야.",
    tags: ["PASTA", "SHRIMP", "ROSE"],
    originInfo: "베이컨: 돼지고기(외국산)",
    nutritionInfo: {
      kcal: 710,
      protein: 24,
      sodium: 1140,
    },
    allergyInfo: "난류, 우유, 대두, 밀, 새우, 돼지고기, 닭고기, 쇠고기, 토마토 함유",
  },
  {
    id: 61,
    img: "/mr-pizza/resources/images/component/menu/pasta-rice/pasta_rice_07.png",
    category: "파스타&라이스",
    line: "pasta",
    title: "베이컨 크림 리조또",
    price: "9,900",
    pick: "꾸덕한 크림으로 채운 든든한 리조또",
    desc: "부드러운 크림소스와 베이컨 풍미가 어우러진 리조또. 고소하고 묵직해서 식사 메뉴로 만족감이 커.",
    tags: ["RISOTTO", "BACON", "CREAM"],
    originInfo: "야채밥: 쌀(외국산), 베이컨: 돼지고기(외국산)",
    nutritionInfo: {
      kcal: 760,
      protein: 21,
      sodium: 1210,
    },
    allergyInfo: "난류, 우유, 대두, 밀, 돼지고기, 닭고기, 쇠고기 함유",
  },

  // ---------- salad-side ----------
  {
    id: 62,
    img: "/mr-pizza/resources/images/component/menu/salad-side/salad_side_01.png",
    category: "샐러드&사이드",
    line: "salad",
    title: "미트치즈프라이즈",
    price: "6,900",
    pick: "고기와 치즈가 듬뿍 올라간 사이드 끝판왕",
    desc: "바삭한 감자 위에 미트소스와 치즈를 풍성하게. 피자와 함께 먹기 좋은 시그니처 사이드.",
    tags: ["FRIES", "MEAT", "CHEESY"],
    isNew: true,
    originInfo: "미트소스: 돼지고기(국산), 쇠고기(호주산)",
    nutritionInfo: {
      kcal: 540,
      protein: 18,
      sodium: 920,
    },
    allergyInfo: "난류, 우유, 대두, 밀, 돼지고기, 쇠고기 함유",
  },
  {
    id: 63,
    img: "/mr-pizza/resources/images/component/menu/salad-side/salad_side_02.png",
    category: "샐러드&사이드",
    line: "salad",
    title: "바베큐윙",
    price: "7,900",
    pick: "달콤한 바베큐 풍미로 즐기는 윙",
    desc: "짭짤한 윙에 바베큐 소스의 달콤한 풍미를 더한 사이드. 피자와 함께 곁들이기 좋은 메뉴야.",
    tags: ["WING", "BBQ", "CHICKEN"],
    isNew: true,
    originInfo: "닭고기(태국산)",
    nutritionInfo: {
      kcal: 430,
      protein: 24,
      sodium: 890,
    },
    allergyInfo: "닭고기, 대두, 밀 함유",
  },
  {
    id: 64,
    img: "/mr-pizza/resources/images/component/menu/salad-side/salad_side_03.png",
    category: "샐러드&사이드",
    line: "salad",
    title: "사이드샘플러",
    price: "8,900",
    pick: "여러 가지 사이드를 한 번에",
    desc: "핫윙, 바베큐윙, 치킨텐더를 한 플레이트에 담은 구성. 뭐 먹을지 고민될 때 고르기 좋아.",
    tags: ["SAMPLER", "SIDE", "VARIETY"],
    isNew: true,
    originInfo: "핫윙: 닭고기(태국산), 바베큐윙: 닭고기(태국산), 치킨텐더: 닭고기(국내산)",
    nutritionInfo: {
      kcal: 610,
      protein: 31,
      sodium: 1280,
    },
    allergyInfo: "대두, 밀, 닭고기, 쇠고기, 달걀 함유",
  },
  {
    id: 65,
    img: "/mr-pizza/resources/images/component/menu/salad-side/salad_side_04.png",
    category: "샐러드&사이드",
    line: "salad",
    title: "치킨텐더(4조각/8조각)",
    price: "4조각 4,900 · 8조각 8,900",
    pick: "겉바속촉 치킨텐더 스테디셀러",
    desc: "바삭한 튀김옷과 부드러운 닭고기 식감이 매력적인 메뉴. 4조각, 8조각 중 취향대로 고를 수 있어.",
    tags: ["CHICKEN", "TENDER", "SIDE"],
    originInfo: "닭고기(국내산)",
    nutritionInfo: {
      4: { kcal: 320, protein: 18, sodium: 540 },
      8: { kcal: 640, protein: 36, sodium: 1080 },
    },
    allergyInfo: "닭고기, 대두, 밀, 달걀, 쇠고기 함유",
  },
  {
    id: 66,
    img: "/mr-pizza/resources/images/component/menu/salad-side/salad_side_05.png",
    category: "샐러드&사이드",
    line: "salad",
    title: "핫윙(4조각/8조각)",
    price: "4조각 4,900 · 8조각 8,900",
    pick: "매콤하게 즐기는 윙 메뉴",
    desc: "짭짤하고 살짝 매콤한 맛이 살아 있는 핫윙. 피자와 함께 먹으면 더 잘 어울리는 사이드야.",
    tags: ["WING", "SPICY", "CHICKEN"],
    originInfo: "닭고기(태국산)",
    nutritionInfo: {
      4: { kcal: 290, protein: 19, sodium: 620 },
      8: { kcal: 580, protein: 38, sodium: 1240 },
    },
    allergyInfo: "닭고기, 대두, 밀 함유",
  },
  {
    id: 67,
    img: "/mr-pizza/resources/images/component/menu/salad-side/salad_side_06.png",
    category: "샐러드&사이드",
    line: "salad",
    title: "미피떡볶이(1인용/매콤,달콤)",
    price: "4,500",
    pick: "매콤달콤하게 즐기는 분식 사이드",
    desc: "쫀득한 떡과 달콤매콤한 소스가 어우러진 1인용 떡볶이. 가볍게 추가하기 좋은 사이드 메뉴야.",
    tags: ["TTEOKBOKKI", "SPICY", "SNACK"],
    originInfo: "",
    nutritionInfo: {
      kcal: 410,
      protein: 9,
      sodium: 860,
    },
    allergyInfo: "우유, 대두, 밀, 닭고기, 쇠고기 함유",
  },
  {
    id: 68,
    img: "/mr-pizza/resources/images/component/menu/salad-side/salad_side_07.png",
    category: "샐러드&사이드",
    line: "salad",
    title: "스파이시 포테이토",
    price: "3,000",
    pick: "세트에 곁들이기 좋은 매콤 포테이토",
    desc: "겉은 바삭하고 속은 포슬한 감자에 스파이시 시즈닝을 더한 사이드. 부담 없이 곁들이기 좋아.",
    tags: ["POTATO", "SPICY", "SIDE"],
    originInfo: "",
    nutritionInfo: {
      kcal: 280,
      protein: 4,
      sodium: 470,
    },
    allergyInfo: "대두, 밀 함유",
  },
  {
    id: 69,
    img: "/mr-pizza/resources/images/component/menu/salad-side/salad_side_08.png",
    category: "샐러드&사이드",
    line: "salad",
    title: "크림치즈바게트",
    price: "6,900",
    pick: "달콤고소한 디저트 느낌 사이드",
    desc: "바삭한 바게트 위에 부드러운 크림치즈를 올린 메뉴. 피자와는 또 다른 결의 고소한 맛이 매력적이야.",
    tags: ["BAGUETTE", "CREAMCHEESE", "SIDE"],
    originInfo: "",
    nutritionInfo: {
      kcal: 460,
      protein: 10,
      sodium: 520,
    },
    allergyInfo: "난류, 우유, 대두, 밀 함유",
  },
  {
    id: 70,
    img: "/mr-pizza/resources/images/component/menu/salad-side/salad_side_09.png",
    category: "샐러드&사이드",
    line: "salad",
    title: "홈샐러드(6구)",
    price: "6,500",
    pick: "상큼하게 곁들이는 밸런스 메뉴",
    desc: "신선한 채소와 토핑을 가볍게 즐길 수 있는 샐러드. 피자와 함께 먹으면 느끼함을 잡아줘.",
    tags: ["SALAD", "FRESH", "LIGHT"],
    originInfo: "",
    nutritionInfo: {
      kcal: 170,
      protein: 5,
      sodium: 260,
    },
    allergyInfo: "난류, 우유, 대두, 밀 함유",
  },

  // ---------- drink ----------
  {
    id: 71,
    img: "/mr-pizza/resources/images/component/menu/drink/drink_01.png",
    category: "음료",
    line: "drink",
    title: "펩시콜라(제로)",
    price: "500ml 1,700 · 1.25L 2,300",
    pick: "깔끔한 탄산으로 마무리",
    desc: "피자와 가장 잘 어울리는 클래식 탄산. 제로 슈가로 부담 없이 즐겨.",
    tags: ["DRINK", "ZERO", "SODA"],
    originInfo: "제조사: 롯데칠성음료",
    nutritionInfo: {
      500: { kcal: 0, sugar: 0 },
      1250: { kcal: 0, sugar: 0 },
    },
    allergyInfo: "해당 없음",
  },
  {
    id: 72,
    img: "/mr-pizza/resources/images/component/menu/drink/drink_02.png",
    category: "음료",
    line: "drink",
    title: "펩시콜라",
    price: "500ml 1,700 · 1.25L 2,300",
    pick: "피자와 가장 잘 맞는 클래식 탄산",
    desc: "익숙한 콜라의 청량감으로 피자의 풍미를 더 살려주는 음료. 기본에 충실한 선택이야.",
    tags: ["DRINK", "COLA", "SODA"],
    originInfo: "제조사: 롯데칠성음료",
    nutritionInfo: {
      500: { kcal: 210, sugar: 53 },
      1250: { kcal: 525, sugar: 132 },
    },
    allergyInfo: "해당 없음",
  },
  {
    id: 73,
    img: "/mr-pizza/resources/images/component/menu/drink/drink_03.png",
    category: "음료",
    line: "drink",
    title: "칠성사이다",
    price: "500ml 1,700 · 1.25L 2,300",
    pick: "상큼한 탄산으로 깔끔하게",
    desc: "상쾌한 탄산감이 특징인 사이다. 느끼함을 잡아주고 입안을 깔끔하게 정리해줘.",
    tags: ["DRINK", "CIDER", "SODA"],
    originInfo: "제조사: 롯데칠성음료",
    nutritionInfo: {
      500: { kcal: 220, sugar: 55 },
      1250: { kcal: 550, sugar: 138 },
    },
    allergyInfo: "해당 없음",
  },

  // ---------- special-set ----------
  {
    id: 74,
    img: "/mr-pizza/resources/images/component/menu/special-set/special_set_01.png",
    setOptions: ["/mr-pizza/resources/images/component/menu/salad-side/salad_side_05.png", "/mr-pizza/resources/images/component/menu/pasta-rice/pasta_rice_03.png"],
    cartImg: "/mr-pizza/resources/images/component/cart/special_set_01.png",
    category: "특제 세트",
    type: "set",
    line: "special",
    title: "쉬림프골드(골드엣지)+홈샐러드(6구)+윙8/오븐",
    price: "M 40,200 · L 45,200",
    pick: "한 번에 즐기는 인기 조합 세트",
    desc: "프리미엄 피자와 샐러드, 윙을 한 번에 담은 구성. 이것저것 따로 고르기 귀찮을 때 고르기 좋은 세트야.",
    tags: ["SET", "BEST", "VALUE"],
    originInfo: "구성품별 원산지 정보는 각 메뉴 참고",
    nutritionInfo: null,
    allergyInfo: "구성품별 상이 (각 메뉴 참고)",
  },
  {
    id: 75,
    img: "/mr-pizza/resources/images/component/menu/special-set/special_set_02.png",
    setOptions: ["/mr-pizza/resources/images/component/menu/salad-side/salad_side_05.png", "/mr-pizza/resources/images/component/menu/pasta-rice/pasta_rice_03.png"],
    cartImg: "/mr-pizza/resources/images/component/cart/special_set_02.png",
    category: "특제 세트",
    type: "set",
    line: "special",
    title: "하프앤하프(골드엣지)+홈샐러드(6구)+윙8/오븐",
    price: "M 40,200 · L 45,200",
    pick: "두 가지 인기 맛을 한 번에",
    desc: "하프앤하프 피자에 샐러드와 윙을 더한 실속 세트. 여러 맛을 고루 즐기고 싶을 때 잘 맞는 구성.",
    tags: ["SET", "HALF&HALF", "VALUE"],
    originInfo: "구성품별 원산지 정보는 각 메뉴 참고",
    nutritionInfo: null,
    allergyInfo: "구성품별 상이 (각 메뉴 참고)",
  },
  {
    id: 76,
    img: "/mr-pizza/resources/images/component/menu/special-set/special_set_03.png",
    setOptions: ["/mr-pizza/resources/images/component/menu/salad-side/salad_side_05.png", "/mr-pizza/resources/images/component/menu/pasta-rice/pasta_rice_03.png"],
    cartImg: "/mr-pizza/resources/images/component/cart/special_set_03.png",
    category: "특제 세트",
    type: "set",
    line: "special",
    title: "포테이토골드(골드엣지)+홈샐러드(6구)+윙8/오븐",
    price: "M 40,200 · L 45,200",
    pick: "고소한 감자 토핑의 스테디 세트",
    desc: "포테이토골드 피자에 홈샐러드와 윙까지 더한 조합. 무난하면서도 만족감 높은 세트 메뉴야.",
    tags: ["SET", "POTATO", "BESTSELLER"],
    originInfo: "구성품별 원산지 정보는 각 메뉴 참고",
    nutritionInfo: null,
    allergyInfo: "구성품별 상이 (각 메뉴 참고)",
  },
  {
    id: 77,
    img: "/mr-pizza/resources/images/component/menu/special-set/special_set_04.png",
    setOptions: ["/mr-pizza/resources/images/component/menu/salad-side/salad_side_05.png", "/mr-pizza/resources/images/component/menu/pasta-rice/pasta_rice_03.png"],
    cartImg: "/mr-pizza/resources/images/component/cart/special_set_04.png",
    category: "특제 세트",
    type: "set",
    line: "special",
    title: "미스터트리오(골드엣지)+홈샐러드(6구)+윙8/오븐",
    price: "M 40,200 · L 45,200",
    pick: "브랜드 대표 메뉴를 세트로",
    desc: "미스터트리오 피자에 샐러드와 윙을 더한 구성. 대표 메뉴를 한 번에 경험하기 좋은 세트야.",
    tags: ["SET", "TRIO", "SIGNATURE"],
    originInfo: "구성품별 원산지 정보는 각 메뉴 참고",
    nutritionInfo: null,
    allergyInfo: "구성품별 상이 (각 메뉴 참고)",
  },
  {
    id: 78,
    img: "/mr-pizza/resources/images/component/menu/special-set/special_set_05.png",
    setOptions: ["/mr-pizza/resources/images/component/menu/salad-side/salad_side_05.png", "/mr-pizza/resources/images/component/menu/pasta-rice/pasta_rice_03.png"],
    cartImg: "/mr-pizza/resources/images/component/cart/special_set_05.png",
    category: "특제 세트",
    type: "set",
    line: "special",
    title: "새우천왕(골드엣지)+홈샐러드(6구)+윙8/오븐",
    price: "M 40,200 · L 45,200",
    pick: "새우 풍미를 제대로 즐기는 세트",
    desc: "탱글한 새우 토핑이 매력적인 피자에 샐러드와 윙을 더한 조합. 해산물 취향이면 만족감 높은 구성.",
    tags: ["SET", "SHRIMP", "PREMIUM"],
    originInfo: "구성품별 원산지 정보는 각 메뉴 참고",
    nutritionInfo: null,
    allergyInfo: "구성품별 상이 (각 메뉴 참고)",
  },
  {
    id: 79,
    img: "/mr-pizza/resources/images/component/menu/special-set/special_set_06.png",
    setOptions: ["/mr-pizza/resources/images/component/menu/salad-side/salad_side_05.png", "/mr-pizza/resources/images/component/menu/pasta-rice/pasta_rice_03.png"],
    cartImg: "/mr-pizza/resources/images/component/cart/special_set_06.png",
    category: "특제 세트",
    type: "set",
    line: "special",
    title: "치즈블라썸스테이크(골드엣지)+홈샐러드(6구)+윙8/오븐",
    price: "M 40,200 · L 45,200",
    pick: "스테이크 풍미를 세트로 푸짐하게",
    desc: "진한 치즈와 스테이크 토핑의 풍미를 중심으로 구성한 세트. 한 끼를 푸짐하게 즐기고 싶을 때 좋아.",
    tags: ["SET", "STEAK", "RICH"],
    originInfo: "구성품별 원산지 정보는 각 메뉴 참고",
    nutritionInfo: null,
    allergyInfo: "구성품별 상이 (각 메뉴 참고)",
  },
  {
    id: 80,
    img: "/mr-pizza/resources/images/component/menu/special-set/special_set_07.png",
    setOptions: ["/mr-pizza/resources/images/component/menu/salad-side/salad_side_05.png", "/mr-pizza/resources/images/component/menu/pasta-rice/pasta_rice_03.png"],
    cartImg: "/mr-pizza/resources/images/component/cart/special_set_07.png",
    category: "특제 세트",
    type: "set",
    line: "special",
    title: "콤비네이션(골드엣지)+홈샐러드(6구)+윙8/오븐",
    price: "M 32,600 · L 38,200",
    pick: "실패 없는 클래식 세트 조합",
    desc: "콤비네이션 피자에 샐러드와 윙을 더한 기본기 탄탄한 세트. 처음 고르기에도 부담 없는 구성이야.",
    tags: ["SET", "CLASSIC", "BALANCED"],
    originInfo: "구성품별 원산지 정보는 각 메뉴 참고",
    nutritionInfo: null,
    allergyInfo: "구성품별 상이 (각 메뉴 참고)",
  },
  {
    id: 81,
    img: "/mr-pizza/resources/images/component/menu/special-set/special_set_08.png",
    setOptions: ["/mr-pizza/resources/images/component/menu/salad-side/salad_side_05.png", "/mr-pizza/resources/images/component/menu/pasta-rice/pasta_rice_03.png"],
    cartImg: "/mr-pizza/resources/images/component/cart/special_set_08.png",
    category: "특제 세트",
    type: "set",
    line: "special",
    title: "불고기(골드엣지)+홈샐러드(6구)+윙8/오븐",
    price: "M 32,600 · L 38,200",
    pick: "달콤짭짤 불고기 세트를 한 번에",
    desc: "불고기 피자의 익숙한 풍미에 샐러드와 윙을 더한 세트 메뉴. 무난하면서도 든든하게 즐기기 좋아.",
    tags: ["SET", "BULGOGI", "VALUE"],
    originInfo: "구성품별 원산지 정보는 각 메뉴 참고",
    nutritionInfo: null,
    allergyInfo: "구성품별 상이 (각 메뉴 참고)",
  },
];

const HERO_IDS = new Set([1, 2, 3, 4, 5]);

const LINE_DEFAULTS = {
  suncrust: {
    defaultEdge: "thin",
    edgeLocked: true,
    allowedEdges: ["thin"],
  },
  solo: {
    defaultEdge: "thin",
    edgeLocked: true,
    allowedEdges: ["thin"],
  },
};

const withDefaults = (item) => ({
  ...item,
  ...(LINE_DEFAULTS[item.line] || {}),
});

export const MENU_ITEMS = RAW_ITEMS.map(withDefaults);

export const HERO_ITEMS = MENU_ITEMS.filter((item) => HERO_IDS.has(Number(item.id))).map((item) => {
  const id = Number(item.id);
  return {
    ...item,
    heroImg: `/mr-pizza/resources/images/component/main/${id}.png`,
  };
});

console.log(
  "MENU_ITEMS ids:",
  MENU_ITEMS.map((v) => [v.id, typeof v.id]),
);
console.log("HERO_ITEMS:", HERO_ITEMS);
